### ISSUE TITLE
Add Social Media Icons to the footer

### ISSUE THREAD

**Issue by Qu-Ack** [Qu-Ack/opensource_starter#11]
Generally the footer of a website contains the links to the socials embedded in icons so your task is to link the instagram handle and linkedin handle of GDG IIIT KOTA with the appropriate icons in the footer

similar to this 

![FOOTer](https://i.ytimg.com/vi/nkZz9DOBzBI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCmTdbuO0BANUO53VZd8_XCpSWzBw)

also add the background color to the footer which will be same as the nav background color. also add a text color of white

**Comment by aparna-u** [comment]
Hi @Qu-Ack , I have updated the Footer section, please verify. PR #22
